apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: serviceuygulamasi
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80